title: Capro
headline: Welcome to your new static Capro site 😎

links:
  Documentation: 'https://capro.xy2z.io'
  Community: https://github.com/xy2z/capro/discussions
  GitHub: https://github.com/xy2z/capro
  Issues: https://github.com/xy2z/capro/issues
  Releases: https://github.com/xy2z/capro/releases
